
package bantotal.dlya.com.uy.btsoa;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.bancosabadell.condusef.Condusef;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Authenticate", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", wsdlLocation = "file:/C:/condusef/Authenticate.wsdl")
public class Authenticate
    extends Service
{

    private final static URL AUTHENTICATE_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATE_EXCEPTION;
    private final static QName AUTHENTICATE_QNAME = new QName("http://uy.com.dlya.bantotal/BTSOA/", "Authenticate");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/condusef/Authenticate.wsdl");
            //url = new URL("Authenticate.wsdl");
        	//url = new URL("https://prod.ibm.mx.bsab:8443/sabadell/servlet/com.dlya.bantotal.odwsbt_Authenticate_v1?wsdl");
        	Properties properties= new Properties();
        	
        	// properties.load(new FileInputStream(new File("configSystem.properties")));
        	ClassLoader loader = Condusef.class.getClassLoader();
        	properties.load(loader.getResourceAsStream("configSystem.properties"));
        	String authenticate = properties.getProperty("mx.bancosabadell.condusef.url.authenticate");
        	System.out.println("Authenticate: " + authenticate);
        	url = new URL(authenticate);
        }catch (IOException ioe) { 
        	e = new WebServiceException(ioe);        
        }
        AUTHENTICATE_WSDL_LOCATION = url;
        AUTHENTICATE_EXCEPTION = e;
    }

    public Authenticate() {
        super(__getWsdlLocation(), AUTHENTICATE_QNAME);
    }

    public Authenticate(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATE_QNAME, features);
    }

    public Authenticate(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATE_QNAME);
    }

    public Authenticate(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATE_QNAME, features);
    }

    public Authenticate(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Authenticate(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AuthenticateSoapPort
     */
    @WebEndpoint(name = "AuthenticateSoapPort")
    public AuthenticateSoapPort getAuthenticateSoapPort() {
        return super.getPort(new QName("http://uy.com.dlya.bantotal/BTSOA/", "AuthenticateSoapPort"), AuthenticateSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AuthenticateSoapPort
     */
    @WebEndpoint(name = "AuthenticateSoapPort")
    public AuthenticateSoapPort getAuthenticateSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uy.com.dlya.bantotal/BTSOA/", "AuthenticateSoapPort"), AuthenticateSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATE_EXCEPTION!= null) {
            throw AUTHENTICATE_EXCEPTION;
        }
        return AUTHENTICATE_WSDL_LOCATION;
    }

}
