
package bantotal.dlya.com.uy.btsoa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommonDataCross", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", wsdlLocation = "file:/C:/condusef/CommonDataCross.wsdl")
public class CommonDataCross
    extends Service
{

    private final static URL COMMONDATACROSS_WSDL_LOCATION;
    private final static WebServiceException COMMONDATACROSS_EXCEPTION;
    private final static QName COMMONDATACROSS_QNAME = new QName("http://uy.com.dlya.bantotal/BTSOA/", "CommonDataCross");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/condusef/CommonDataCross.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMMONDATACROSS_WSDL_LOCATION = url;
        COMMONDATACROSS_EXCEPTION = e;
    }

    public CommonDataCross() {
        super(__getWsdlLocation(), COMMONDATACROSS_QNAME);
    }

    public CommonDataCross(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMONDATACROSS_QNAME, features);
    }

    public CommonDataCross(URL wsdlLocation) {
        super(wsdlLocation, COMMONDATACROSS_QNAME);
    }

    public CommonDataCross(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMONDATACROSS_QNAME, features);
    }

    public CommonDataCross(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommonDataCross(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CommonDataCrossSoapPort
     */
    @WebEndpoint(name = "CommonDataCrossSoapPort")
    public CommonDataCrossSoapPort getCommonDataCrossSoapPort() {
        return super.getPort(new QName("http://uy.com.dlya.bantotal/BTSOA/", "CommonDataCrossSoapPort"), CommonDataCrossSoapPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonDataCrossSoapPort
     */
    @WebEndpoint(name = "CommonDataCrossSoapPort")
    public CommonDataCrossSoapPort getCommonDataCrossSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uy.com.dlya.bantotal/BTSOA/", "CommonDataCrossSoapPort"), CommonDataCrossSoapPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMMONDATACROSS_EXCEPTION!= null) {
            throw COMMONDATACROSS_EXCEPTION;
        }
        return COMMONDATACROSS_WSDL_LOCATION;
    }

}
