
package bantotal.dlya.com.uy.btsoa;

import java.io.IOException;
import java.net.URL;
import java.util.Properties;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import mx.bancosabadell.condusef.Condusef;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CommonDataCross", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", wsdlLocation = "file:/C:/condusef/CommonDataCross.wsdl")
public class CommonDataCross
    extends Service
{
	/**
	 * COMMONDATACROSS_WSDL_LOCATION property.
	 */
    private final static URL COMMONDATACROSS_WSDL_LOCATION;
    
    /**
     * COMMONDATACROSS_EXCEPTION property.
     */
    private final static WebServiceException COMMONDATACROSS_EXCEPTION;
    
    /**
     * COMMONDATACROSS_QNAME property.
     */
    private final static QName COMMONDATACROSS_QNAME = new QName("http://uy.com.dlya.bantotal/BTSOA/", "CommonDataCross");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            //url = new URL("file:/C:/condusef/CommonDataCross.wsdl");
        	//url = new URL("CommonDataCross.wsdl");
        	//url = new URL("https://prod.ibm.mx.bsab:8443/sabadell/servlet/com.dlya.bantotal.odwsbt_CommonDataCross_v1?wsdl");
        	Properties properties= new Properties();
        	//properties.load(new FileInputStream(new File("configSystem.properties")));
        	ClassLoader loader = Condusef.class.getClassLoader();
        	properties.load(loader.getResourceAsStream("configSystem.properties"));
        	String commonDataCross = properties.getProperty("mx.bancosabadell.condusef.url.commonDataCross");
        	System.out.println("commonDataCross: " + commonDataCross);
        	//url = new URL("http://es9tc06bsab.mx.bsab:17153/sabadell/servlet/com.dlya.bantotal.odwsbt_CommonDataCross_v1?wsdl");
        	url = new URL(commonDataCross);
        } catch (IOException ex) {
            e = new WebServiceException(ex);
        }
        COMMONDATACROSS_WSDL_LOCATION = url;
        COMMONDATACROSS_EXCEPTION = e;
    }

    /**
     * Generic constructor. 
     */
    public CommonDataCross() {
        super(__getWsdlLocation(), COMMONDATACROSS_QNAME);
    }

    /**
     * Constructor with features.
     * @param features List of features.
     */
    public CommonDataCross(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMMONDATACROSS_QNAME, features);
    }

    /**
     * Constructor with WSDL location.
     * @param wsdlLocation URL of WSDL location.
     */
    public CommonDataCross(URL wsdlLocation) {
        super(wsdlLocation, COMMONDATACROSS_QNAME);
    }

    /**
     * Constructor with WSDL location and features.
     * @param wsdlLocation URL of WSDL location.
     * @param features List of features.
     */
    public CommonDataCross(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMMONDATACROSS_QNAME, features);
    }
    
    /**
     * Constructor with WSDL location and service name. 
     * @param wsdlLocation URL of WSDL location.
     * @param serviceName Service name.
     */
    public CommonDataCross(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Constructor with WSDL location, service name and features.
     * @param wsdlLocation URL of WSDL location.
     * @param serviceName Service name.
     * @param features List of features.
     */
    public CommonDataCross(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * Method for get the SOAP port.
     * @return
     *     returns CommonDataCrossSoapPort SOAP port.
     */
    @WebEndpoint(name = "CommonDataCrossSoapPort")
    public CommonDataCrossSoapPort getCommonDataCrossSoapPort() {
        return super.getPort(new QName("http://uy.com.dlya.bantotal/BTSOA/", "CommonDataCrossSoapPort"), CommonDataCrossSoapPort.class);
    }

    /**
     * Method for get the SOAP port with feature.
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommonDataCrossSoapPort SOAP port.
     */
    @WebEndpoint(name = "CommonDataCrossSoapPort")
    public CommonDataCrossSoapPort getCommonDataCrossSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://uy.com.dlya.bantotal/BTSOA/", "CommonDataCrossSoapPort"), CommonDataCrossSoapPort.class, features);
    }

    /**
     * Method for get WSD location.
     * @return WSDL location.
     */
    private static URL __getWsdlLocation() {
        if (COMMONDATACROSS_EXCEPTION!= null) {
            throw COMMONDATACROSS_EXCEPTION;
        }
        return COMMONDATACROSS_WSDL_LOCATION;
    }

}
