
package bantotal.dlya.com.uy.btsoa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommonDataCrossSoapPort", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommonDataCrossSoapPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossEvaluateReferralResponse
     */
    @WebMethod(operationName = "EvaluateReferral", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.EvaluateReferral")
    @WebResult(name = "CommonDataCross.EvaluateReferralResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossEvaluateReferralResponse evaluateReferral(
        @WebParam(name = "CommonDataCross.EvaluateReferral", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossEvaluateReferral parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossEvaluateSecurityQuestionsResponse
     */
    @WebMethod(operationName = "EvaluateSecurityQuestions", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.EvaluateSecurityQuestions")
    @WebResult(name = "CommonDataCross.EvaluateSecurityQuestionsResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossEvaluateSecurityQuestionsResponse evaluateSecurityQuestions(
        @WebParam(name = "CommonDataCross.EvaluateSecurityQuestions", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossEvaluateSecurityQuestions parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossExecuteContractCaseResponse
     */
    @WebMethod(operationName = "ExecuteContractCase", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.ExecuteContractCase")
    @WebResult(name = "CommonDataCross.ExecuteContractCaseResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossExecuteContractCaseResponse executeContractCase(
        @WebParam(name = "CommonDataCross.ExecuteContractCase", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossExecuteContractCase parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRegisterCaseResponse
     */
    @WebMethod(operationName = "RegisterCase", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RegisterCase")
    @WebResult(name = "CommonDataCross.RegisterCaseResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRegisterCaseResponse registerCase(
        @WebParam(name = "CommonDataCross.RegisterCase", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRegisterCase parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRegisterReferralResponse
     */
    @WebMethod(operationName = "RegisterReferral", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RegisterReferral")
    @WebResult(name = "CommonDataCross.RegisterReferralResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRegisterReferralResponse registerReferral(
        @WebParam(name = "CommonDataCross.RegisterReferral", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRegisterReferral parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveActivitiesResponse
     */
    @WebMethod(operationName = "RetrieveActivities", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveActivities")
    @WebResult(name = "CommonDataCross.RetrieveActivitiesResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveActivitiesResponse retrieveActivities(
        @WebParam(name = "CommonDataCross.RetrieveActivities", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveActivities parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveBankResponse
     */
    @WebMethod(operationName = "RetrieveBank", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveBank")
    @WebResult(name = "CommonDataCross.RetrieveBankResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveBankResponse retrieveBank(
        @WebParam(name = "CommonDataCross.RetrieveBank", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveBank parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveBanksResponse
     */
    @WebMethod(operationName = "RetrieveBanks", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveBanks")
    @WebResult(name = "CommonDataCross.RetrieveBanksResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveBanksResponse retrieveBanks(
        @WebParam(name = "CommonDataCross.RetrieveBanks", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveBanks parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveBase64ContractResponse
     */
    @WebMethod(operationName = "RetrieveBase64Contract", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveBase64Contract")
    @WebResult(name = "CommonDataCross.RetrieveBase64ContractResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveBase64ContractResponse retrieveBase64Contract(
        @WebParam(name = "CommonDataCross.RetrieveBase64Contract", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveBase64Contract parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveBase64DocWithIDResponse
     */
    @WebMethod(operationName = "RetrieveBase64DocWithID", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveBase64DocWithID")
    @WebResult(name = "CommonDataCross.RetrieveBase64DocWithIDResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveBase64DocWithIDResponse retrieveBase64DocWithID(
        @WebParam(name = "CommonDataCross.RetrieveBase64DocWithID", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveBase64DocWithID parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveBase64DocumentResponse
     */
    @WebMethod(operationName = "RetrieveBase64Document", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveBase64Document")
    @WebResult(name = "CommonDataCross.RetrieveBase64DocumentResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveBase64DocumentResponse retrieveBase64Document(
        @WebParam(name = "CommonDataCross.RetrieveBase64Document", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveBase64Document parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveCompanyLinkResponse
     */
    @WebMethod(operationName = "RetrieveCompanyLink", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveCompanyLink")
    @WebResult(name = "CommonDataCross.RetrieveCompanyLinkResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveCompanyLinkResponse retrieveCompanyLink(
        @WebParam(name = "CommonDataCross.RetrieveCompanyLink", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveCompanyLink parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveDocumentsTypeResponse
     */
    @WebMethod(operationName = "RetrieveDocumentsType", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveDocumentsType")
    @WebResult(name = "CommonDataCross.RetrieveDocumentsTypeResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveDocumentsTypeResponse retrieveDocumentsType(
        @WebParam(name = "CommonDataCross.RetrieveDocumentsType", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveDocumentsType parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveOccupationResponse
     */
    @WebMethod(operationName = "RetrieveOccupation", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveOccupation")
    @WebResult(name = "CommonDataCross.RetrieveOccupationResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveOccupationResponse retrieveOccupation(
        @WebParam(name = "CommonDataCross.RetrieveOccupation", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveOccupation parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveProfessionsResponse
     */
    @WebMethod(operationName = "RetrieveProfessions", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveProfessions")
    @WebResult(name = "CommonDataCross.RetrieveProfessionsResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveProfessionsResponse retrieveProfessions(
        @WebParam(name = "CommonDataCross.RetrieveProfessions", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveProfessions parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveReferenceTypesResponse
     */
    @WebMethod(operationName = "RetrieveReferenceTypes", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveReferenceTypes")
    @WebResult(name = "CommonDataCross.RetrieveReferenceTypesResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveReferenceTypesResponse retrieveReferenceTypes(
        @WebParam(name = "CommonDataCross.RetrieveReferenceTypes", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveReferenceTypes parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveReferralListResponse
     */
    @WebMethod(operationName = "RetrieveReferralList", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveReferralList")
    @WebResult(name = "CommonDataCross.RetrieveReferralListResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveReferralListResponse retrieveReferralList(
        @WebParam(name = "CommonDataCross.RetrieveReferralList", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveReferralList parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveRewardTotalResponse
     */
    @WebMethod(operationName = "RetrieveRewardTotal", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveRewardTotal")
    @WebResult(name = "CommonDataCross.RetrieveRewardTotalResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveRewardTotalResponse retrieveRewardTotal(
        @WebParam(name = "CommonDataCross.RetrieveRewardTotal", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveRewardTotal parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveRewardsResponse
     */
    @WebMethod(operationName = "RetrieveRewards", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveRewards")
    @WebResult(name = "CommonDataCross.RetrieveRewardsResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveRewardsResponse retrieveRewards(
        @WebParam(name = "CommonDataCross.RetrieveRewards", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveRewards parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveSecurityQuestionsResponse
     */
    @WebMethod(operationName = "RetrieveSecurityQuestions", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveSecurityQuestions")
    @WebResult(name = "CommonDataCross.RetrieveSecurityQuestionsResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveSecurityQuestionsResponse retrieveSecurityQuestions(
        @WebParam(name = "CommonDataCross.RetrieveSecurityQuestions", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveSecurityQuestions parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveStatusMaritalResponse
     */
    @WebMethod(operationName = "RetrieveStatusMarital", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveStatusMarital")
    @WebResult(name = "CommonDataCross.RetrieveStatusMaritalResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveStatusMaritalResponse retrieveStatusMarital(
        @WebParam(name = "CommonDataCross.RetrieveStatusMarital", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveStatusMarital parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossRetrieveUDISValueResponse
     */
    @WebMethod(operationName = "RetrieveUDISValue", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.RetrieveUDISValue")
    @WebResult(name = "CommonDataCross.RetrieveUDISValueResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossRetrieveUDISValueResponse retrieveUDISValue(
        @WebParam(name = "CommonDataCross.RetrieveUDISValue", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossRetrieveUDISValue parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossSendMailResponse
     */
    @WebMethod(operationName = "SendMail", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.SendMail")
    @WebResult(name = "CommonDataCross.SendMailResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossSendMailResponse sendMail(
        @WebParam(name = "CommonDataCross.SendMail", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossSendMail parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossSendSMSResponse
     */
    @WebMethod(operationName = "SendSMS", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.SendSMS")
    @WebResult(name = "CommonDataCross.SendSMSResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossSendSMSResponse sendSMS(
        @WebParam(name = "CommonDataCross.SendSMS", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossSendSMS parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns bantotal.dlya.com.uy.btsoa.CommonDataCrossUpdateReferralResponse
     */
    @WebMethod(operationName = "UpdateReferral", action = "http://uy.com.dlya.bantotal/BTSOA/action/ACOMMONDATACROSS.UpdateReferral")
    @WebResult(name = "CommonDataCross.UpdateReferralResponse", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
    public CommonDataCrossUpdateReferralResponse updateReferral(
        @WebParam(name = "CommonDataCross.UpdateReferral", targetNamespace = "http://uy.com.dlya.bantotal/BTSOA/", partName = "parameters")
        CommonDataCrossUpdateReferral parameters);

}
